Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,14 +8,13 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
-
-      - name: Copy files to Hetzner
-        uses: appleboy/scp-action@master
-        with:
-          host: 178.104.70.62
-          username: root
-          password: ${{ secrets.VPS_PASSWORD }}
-          source: "."
-          target: "/var/www/lumina"
+      - name: Update Hetzner
+        run: |
+          sudo apt-get install -y sshpass
+          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@178.104.70.62 "
+            if [ -d '/var/www/lumina' ]; then
+              cd /var/www/lumina && git fetch --all && git reset --hard origin/main
+            else
+              echo 'Folder /var/www/lumina not found!' && exit 1
+            fi
+          "
